### ISSUE TITLE
NPE when creating generic type

### ISSUE THREAD

**Issue by pwfcurry** [FlexTradeUKLtd/jfixture#29] opened 2016-07-21 08:33 UTC
```java
public class TestClass {

  private final TestContainer<String> container;

  public TestClass(TestContainer<String> container) {
    this.container = container;
  }


  public class TestContainer<T> {

    private final T value;

    public TestContainer(T value) {
      this.value = value;
    }
  }


  public static void main(String[] args) {
    new JFixture().create(TestClass.class);
  }

}
```

Running the above code causes JFixture v2.5.1 to throw a NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at com.flextrade.jfixture.utility.SpecimenType.<init>(SpecimenType.java:37)
	at com.flextrade.jfixture.utility.SpecimenType$3.<init>(SpecimenType.java:55)
	at com.flextrade.jfixture.utility.SpecimenType.withGenericContext(SpecimenType.java:55)
	at com.flextrade.jfixture.utility.ParameterUtils.convertPossibleGenericTypeToSpecimenType(ParameterUtils.java:50)
```

**Comment by richkeenan** [comment] 2016-07-25 09:03
Java and generics. The bane of my life. Thanks @pwfcurry I'll take a look

**Comment by richkeenan** [comment] 2016-07-25 09:37
Interestingly this works fine if `TestContainer` isn't an inner clsas

**Comment by richkeenan** [comment] 2016-07-25 09:55
As suspected, this isn't an issue with Generics, it's an issue with the inner type. Your definition would cause a circular reference as `TestClass` requires `TestContainer` in the constructor but `TestContainer` implicitly takes an instance of `TestClass` because it's an inner class not marked as static.

You can't create an instance of `TestClass` whether you're using JFixture or not (unless you pass a `null` `TestContainer` in). If you modify `TestContainer` to be `static` JFixture will handle this correctly.

Maybe your simplified example is missing something else that your actual code has? I'm closing this issue but if you can reproduce it (and be able to create the class in 'regular' Java) please raise a new issue and I'll love to look into it.

**Closed by richkeenan** 2016-07-25 09:55 UTC

**Comment by pwfcurry** [comment] 2016-08-01 09:47
Oops, bad example. I still see the same problem hwen TestContainer is static, also when it's not a static inner class.
